/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_rectangle_free(a: number): void;
export function __wbg_get_rectangle_id(a: number): number;
export function __wbg_set_rectangle_id(a: number, b: number): void;
export function __wbg_get_rectangle_collision(a: number): number;
export function __wbg_set_rectangle_collision(a: number, b: number): void;
export function __wbg_get_rectangle_width(a: number): number;
export function __wbg_set_rectangle_width(a: number, b: number): void;
export function __wbg_get_rectangle_height(a: number): number;
export function __wbg_set_rectangle_height(a: number, b: number): void;
export function __wbg_get_rectangle_x(a: number): number;
export function __wbg_set_rectangle_x(a: number, b: number): void;
export function __wbg_get_rectangle_y(a: number): number;
export function __wbg_set_rectangle_y(a: number, b: number): void;
export function __wbg_get_rectangle_vx(a: number): number;
export function __wbg_set_rectangle_vx(a: number, b: number): void;
export function __wbg_get_rectangle_vy(a: number): number;
export function __wbg_set_rectangle_vy(a: number, b: number): void;
export function __wbg_get_rectangle_ax(a: number): number;
export function __wbg_set_rectangle_ax(a: number, b: number): void;
export function __wbg_get_rectangle_ay(a: number): number;
export function __wbg_set_rectangle_ay(a: number, b: number): void;
export function __wbg_get_rectangle_mass(a: number): number;
export function __wbg_set_rectangle_mass(a: number, b: number): void;
export function __wbg_engine_free(a: number): void;
export function engine_new(a: number, b: number, c: number, d: number): number;
export function engine_reset(a: number): void;
export function engine_generate(a: number, b: number): void;
export function engine_add_rect(a: number, b: number): void;
export function engine_set_damping(a: number, b: number): void;
export function engine_set_gravity_enabled(a: number, b: number): void;
export function engine_set_collision_enabled(a: number, b: number): void;
export function engine_set_elastic_enabled(a: number, b: number): void;
export function engine_set_gravity_constant(a: number, b: number): void;
export function engine_set_sun_mass(a: number, b: number): void;
export function engine_get_rects(a: number): number;
export function engine_tick(a: number, b: number): void;
